class VideoAttributes

  MEDICINE = "Medicine"
  SURGERY = "Surgery"
  ANESTHESIA = "Anesthesia"
  RADIOLOGY = "Radiology"
  PEDIATRICS = "Pediatrics"
  OBGYN = "Ob/gyn"
  OTHER = "Other"
  ALL = "All"
  PSYCH = "Psych"
  NEURO = "Neuro"

  @categories_by_id =  {
    '5uBE4uuTEMQ' => MEDICINE,
    'ta9KNbcq-KI' => MEDICINE,
    'azvTa06_LTo' => MEDICINE,
    'NRQ8WzCi0ds' => MEDICINE,
    'XGjB-tzdSlE' => MEDICINE,
    'T3xFzsgJBkU' => MEDICINE,
    '4fP7-XgSZnQ' => MEDICINE,
    'yoJzNL6XqkI' => MEDICINE,
    'wAMis_HNZWE' => MEDICINE,
    '3CyKCe8B894' => MEDICINE,
    'nopHyyI2vPY' => MEDICINE,
    'jzVBNyI9Ay8' => MEDICINE,
    'VACDx6QTJv4' => MEDICINE,
    '7w3F-U6j1yU' => MEDICINE,
    '63tXOFlDQS8' => MEDICINE,
    'A_lrwKVLNNE' => MEDICINE,
    'uRk6XVw4pnw' => MEDICINE,
    'oaKlGcatP9E' => MEDICINE,
    'coBiupgFCLo' => MEDICINE,  #new
    'lpHJP-oaLvI' => MEDICINE,
    'WF1s01ePXLI' => MEDICINE,
    'y5TZT1IaQns' => MEDICINE,
    'H-pajljT5qE' => MEDICINE,
    'az_PyTXFG9c' => MEDICINE,
    'Xq9LFn7ddj8' => MEDICINE,
    '9-j0T63pQsc' => MEDICINE,
    'DHxSE2Y3Bb4' => MEDICINE,
    'rFOLkjCQVFA' => MEDICINE, #new
    'AO9Xg2Jn8Rg' => MEDICINE,
    'r0szxqTVGtY' => MEDICINE,
    'iUjCfCwbKFA' => MEDICINE,
    'L4ZO00A5pUA' => MEDICINE,
    'ncpZQV0kZ2A' => MEDICINE,
    'A1oBUzrx05Y' => MEDICINE,
    'RsSudJZ7V1E' => MEDICINE,
    'we3MkFBL9aA' => MEDICINE,
    'MnuYVwyWZ8E' => MEDICINE,
    'OTwtsHH-Uxc' => MEDICINE,
    '2jD0RXdNYas' => SURGERY,
    'o-dkb-YX3-E' => SURGERY,
    'Q0X2cP3C8R8' => SURGERY,
    '-1m87_1D_jc' => SURGERY,
    'UybrrVVOFCY' => ANESTHESIA,
    'JXffYwYlnKQ' => ANESTHESIA,
    '56YtlSy62D0' => ANESTHESIA,
    'GSDQzS_FcNc' => ANESTHESIA,
    '8ZAN6vEuYjY' => RADIOLOGY,
    'oEmCcEio6nw' => RADIOLOGY,
    'F8TYLT0-5fs' => RADIOLOGY,
    'W_6v0v6tqCE' => RADIOLOGY,
    'DnBRarZKvoU' => RADIOLOGY,
    '7tDDDLqWnBQ' => RADIOLOGY,
    '4NNhGSXvbOU' => RADIOLOGY,
    '4oYBLkbDjhg' => RADIOLOGY,
    'z7_HseZBTT0' => RADIOLOGY,
    'iEPCWQ64-pc' => PEDIATRICS,
    'i0fnBTUuRIA' => PEDIATRICS,
    'sBNt5H9FIwc' => PEDIATRICS,
    'c91T3fW5p1o' => OBGYN,
    'xDlwAry1HHY' => OBGYN,
    'vpw0bKOTDrs' => OBGYN,
    'YO6TzRwzQFU' => OBGYN,
    'R6XGStFZz_Q' => OBGYN,
    '4x1DoKYZucE' => OBGYN,
    'ZueWWFQNAcQ' => OBGYN,
    'MVDKrQorC4A' => PSYCH,
    'PRcl4Ihdcng' => NEURO,
    'eLqtVFbYwJc' => NEURO,
    'suAwmQaTmUE' => NEURO
  }

  @order_by_id =  {
      '5uBE4uuTEMQ' => 1,
      'ta9KNbcq-KI' => 2,
      'azvTa06_LTo' => 3,
      'NRQ8WzCi0ds' => 4,
      'XGjB-tzdSlE' => 5,
      'T3xFzsgJBkU' => 6,
      '4fP7-XgSZnQ' => 7,
      'yoJzNL6XqkI' => 8,
      'wAMis_HNZWE' => 9,
      '3CyKCe8B894' => 10,
      'nopHyyI2vPY' => 11,
      'jzVBNyI9Ay8' => 12,
      'VACDx6QTJv4' => 13,
      '7w3F-U6j1yU' => 14,
      '63tXOFlDQS8' => 15,
      'A_lrwKVLNNE' => 16,
      'uRk6XVw4pnw' => 17,
      'oaKlGcatP9E' => 18,
      'coBiupgFCLo' => 19,
      'lpHJP-oaLvI' => 20,
      'WF1s01ePXLI' => 21,
      'y5TZT1IaQns' => 22,
      'H-pajljT5qE' => 23,
      'az_PyTXFG9c' => 24,
      'Xq9LFn7ddj8' => 25,
      '9-j0T63pQsc' => 26,
      'DHxSE2Y3Bb4' => 27,
      'rFOLkjCQVFA' => 28,
      'AO9Xg2Jn8Rg' => 29,
      'r0szxqTVGtY' => 30,
      'iUjCfCwbKFA' => 31,
      'L4ZO00A5pUA' => 32,
      'ncpZQV0kZ2A' => 33,
      'A1oBUzrx05Y' => 34,
      'RsSudJZ7V1E' => 35,
      'we3MkFBL9aA' => 36,
      'MnuYVwyWZ8E' => 37,
      'OTwtsHH-Uxc' => 38,
      '2jD0RXdNYas' => 39,
      'o-dkb-YX3-E' => 40,
      'Q0X2cP3C8R8' => 41,
      '-1m87_1D_jc' => 42,
      'UybrrVVOFCY' => 43,
      'JXffYwYlnKQ' => 44,
      '56YtlSy62D0' => 45,
      'GSDQzS_FcNc' => 46,
      '8ZAN6vEuYjY' => 47,
      'oEmCcEio6nw' => 48,
      'F8TYLT0-5fs' => 49,
      'W_6v0v6tqCE' => 50,
      'DnBRarZKvoU' => 51,
      '7tDDDLqWnBQ' => 52,
      '4NNhGSXvbOU' => 53,
      '4oYBLkbDjhg' => 54,
      'z7_HseZBTT0' => 55,
      'iEPCWQ64-pc' => 56,
      'i0fnBTUuRIA' => 57,
      'sBNt5H9FIwc' => 58,
      'c91T3fW5p1o' => 59,
      'xDlwAry1HHY' => 60,
      'vpw0bKOTDrs' => 61,
      'YO6TzRwzQFU' => 62,
      'R6XGStFZz_Q' => 63,
      '4x1DoKYZucE' => 64,
      'ZueWWFQNAcQ' => 65,
      'MVDKrQorC4A' => 66,
      'PRcl4Ihdcng' => 67,
      'eLqtVFbYwJc' => 68,
      'suAwmQaTmUE' => 69
  }


  def self.find_category(id)
      return @categories_by_id[id]
  end

  def self.find_order(id)
    return @order_by_id[id]
  end
end